version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: requirements/nginx/Dockerfile
    container_name: nginx
    volumes:
      - ./requirements/nginx/conf/:/etc/nginx/http.d/
      - ./requirements/nginx/tools/:/etc/nginx/ssl/
      - wordpress:/var/www/
    ports:
      - "443:443"
    networks:
      - inception
    restart: always
  mariadb:
    build:
      context: .
      dockerfile: requirements/mariaDB/Dockerfile
    container_name: mariadb
    networks:
      - inception
    restart: always
  wordpress:
    build:
      context: .
      dockerfile: requirements/wordpress/Dockerfile
    container_name: wordpress
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/
    networks:
      - inception
    restart: always
    
volumes:
  wordpress:
    driver_opts:
      o: bind
      type: none
      device: /Users/pooneh/data/wordpress
  mariadb:
    driver_opts:
      o: bind
      type: none
      device: /Users/pooneh/data/mariadb

networks:
  inception:
    name: inception
    driver: bridge